### ISSUE TITLE
Object reference not set to an instance of an object at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()

### ISSUE THREAD

**Issue by edchapel** [madskristensen/WebEssentials2012#1]
Using Visual Studio 2012 Premuim

I have a solution with (too) many projects and many solution folders.
1. Right-click the Solution root node
2. Click Build

I receive the following in my build output:

```
========== Build: 9 succeeded, 0 failed, 23 up-to-date, 3 skipped ==========
10/6/2013 6:00:28 PM: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
10/6/2013 6:00:28 PM: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
10/6/2013 6:00:28 PM: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
10/6/2013 6:00:28 PM: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
10/6/2013 6:00:28 PM: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
10/6/2013 6:00:28 PM: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
10/6/2013 6:00:28 PM: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
```

I created a small solution to demonstrate the issue.

https://dl.dropboxusercontent.com/u/378540/WebEssentials2012Issue1.zip

**Comment by Nettsentrisk** [comment]
Should I still be getting this error? In latest version, 3.2.
