### ISSUE TITLE
LESS recompile causes VS 2012 to crash

### ISSUE THREAD

**Issue by TradeArcher2020** [madskristensen/WebEssentials2012#17]
If the generated CSS file is under source control and marked Read-Only, then when the LESS file tries to recompile the CSS there is an error and VS 2012 crashes. This can be solved by marking the generated CSS file as DependentUpon the corresponding LESS file.

This behavior is occurring for me in a Windows Store (WindJS) project where I have taken existing CSS files and renamed them to LESS files so I can take advantage of Web Essentials LESS compiler in the project. The problem is that it does not generate the CSS files as nested files under the LESS file. Doing so would ensure that all of the files are checked out when I begin editing the LESS file.

**Comment by ghost** [comment]
I am running into the same issue. In VS 2012, VS totally crashes when editing a LESS file and the related .css and min.css files are not checked out. In VS2013, VS does not crash.

The problem I see is in VS2013, the dependent .css and .min.css files (unless they are checked out) never get updated. When I edit the LESS file, it gets checked out automatically, but the other files don't. They are setup as DependentUpon as the other poster suggested--but even with that they don't get checked out automatically.

Since the files aren't checked out, the LESS compiler bombs when trying to create/update the .css and .min.css files:

System.UnauthorizedAccessException: Access to the path '<blah>.css' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at MadsKristensen.EditorExtensions.MarginBase.WriteFile(String content, String fileName, Boolean fileExist, Boolean fileWritten)

Any ideas on how to get VS to automatically check out the .css and .min.css files when editing the LESS file?
