### ISSUE TITLE
Errors on project build

### ISSUE THREAD

**Issue by jtsom** [madskristensen/WebEssentials2012#34]
When building my project, I'm seeing about 15 of these in the build output:

12/30/2013 10:34:31 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()

**Comment by jtsom** [comment]
Another update.. and this still is happening:

1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/16/2014 8:18:26 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()

**Comment by joshSzep** [comment]
Confirm this also happens for me. It does not happen with every solution, but one specifically. Unfortunately I can not share the solution, but it is an ASP.NET WebForms project which was just upgraded through the auto-migrator from VS2010 to VS2012 

Here is my Visual Studio Info:

```
Microsoft Visual Studio Professional 2012
Version 11.0.61030.00 Update 4
Microsoft .NET Framework
Version 4.5.50709

Installed Version: Professional

LightSwitch for Visual Studio 2012   XXXXX-XXX-XXXXXXX-XXXXX
Microsoft LightSwitch for Visual Studio 2012

Office Developer Tools   XXXXX-XXX-XXXXXXX-XXXXX
Microsoft Office Developer Tools

Team Explorer for Visual Studio 2012   XXXXX-XXX-XXXXXXX-XXXXX
Microsoft Team Explorer for Visual Studio 2012

Visual Basic 2012   XXXXX-XXX-XXXXXXX-XXXXX
Microsoft Visual Basic 2012

Visual C# 2012   XXXXX-XXX-XXXXXXX-XXXXX
Microsoft Visual C# 2012

Visual C++ 2012   XXXXX-XXX-XXXXXXX-XXXXX
Microsoft Visual C++ 2012

Visual F# 2012   XXXXX-XXX-XXXXXXX-XXXXX
Microsoft Visual F# 2012

Visual Studio 2012 Code Analysis Spell Checker   XXXXX-XXX-XXXXXXX-XXXXX
Microsoft® Visual Studio® 2012 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Visual Studio 2012 SharePoint Developer Tools   XXXXX-XXX-XXXXXXX-XXXXX
Microsoft Visual Studio 2012 SharePoint Developer Tools

AlignAssignments   1.0
Command for aligning assignments.

ASP.NET and Web Tools   2012.3.41009
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Windows Azure Web Sites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Windows Azure

AutoBraceComplete   1.0
auto brace complete

Color Theme Designer   1.0
Designer for creating new color themes

CustomDocWell   1.0
Provides configurable behavior for the document well in Visual Studio 2012.

Entity Framework Power Tools   1.0
Adds useful design-time DbContext features to the Visual Studio Solution Explorer context menu. 

When right-clicking on a file containing a derived DbContext class, the following context menu functions are supported:

1) View Entity Data Model - Displays the underlying Code First model in the Entity Framework designer.
2) View Entity Data Model XML - Displays the EDMX XML representing the underlying Code First model.
3) Generate Views - Generates pre-compiled views used by the EF runtime to improve start-up performance. Adds the generated views file to the containing project.

File Nesting   1.0
Automatically nest files based on file name and enables developers to nest and unnest any file manually

Git Source Control Provider   1.0.0.0


Indent Guides   14
Indent Guides

Adds visual guides at each indentation level.

JetBrains dotCover 2.7   Full Edition build 2.7.0.662 on 2014-03-21T02:09:54
JetBrains dotCover 2.7 package for Microsoft Visual Studio. For more information about dotCover, visit http://www.jetbrains.com/dotcover/. Copyright © 2009–2014 JetBrains, Inc.

JetBrains ReSharper 8.2   C# Edition build 8.2.0.2160 on 2014-03-21T00:53:08
JetBrains ReSharper 8.2 package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper/. Copyright © 2003–2014 JetBrains, Inc.

NuGet Package Manager   2.8.50313.31
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

OptionsPageImpl   1.0
Information about my package

PowerCommands for Visual Studio 2010   1.0
A set of power commands for Visual Studio 2010

PreEmptive Analytics Visualizer   1.0
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Quick Launch Tasks   1.0
Microsoft Quick LaunchTasks package adds accessibility and settings tasks to the Quick Launch tool.

SQL Server Data Tools   11.1.31203.1
Microsoft SQL Server Data Tools

Visual Studio 11 Editor Extension   1.0
Information about my package

VS10x CodeMap Package   1.1
Powerful Visual Studio code editor visualizer (C# and VB).

VS10x Method Block Highlighter Package   1.2
Highlight entire methods with a colored background (green, yellow, cyan, magenta)
```

Here is my system info:

```
OS Name Microsoft Windows 8 Pro
Version 6.2.9200 Build 9200
Other OS Description    Not Available
OS Manufacturer Microsoft Corporation
System Name XXXXXXXXX
System Manufacturer VMware, Inc.
System Model    VMware Virtual Platform
System Type x64-based PC
System SKU  
Processor   Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz, 2692 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date   Phoenix Technologies LTD 6.00, 7/2/2012
SMBIOS Version  2.4
Embedded Controller Version 0.00
BIOS Mode   Legacy
BaseBoard Manufacturer  Intel Corporation
BaseBoard Model Not Available
BaseBoard Name  Base Board
Platform Role   Mobile
Secure Boot State   Unsupported
PCR7 Configuration  Not Available
Windows Directory   C:\WINDOWS
System Directory    C:\WINDOWS\system32
Boot Device \Device\HarddiskVolume1
Locale  United States
Hardware Abstraction Layer  Version = "6.2.9200.16442"
User Name   XXXXXXXXXXXXXX
Time Zone   Central Daylight Time
Installed Physical Memory (RAM) 3.97 GB
Total Physical Memory   3.97 GB
Available Physical Memory   708 MB
Total Virtual Memory    9.72 GB
Available Virtual Memory    2.09 GB
Page File Space 5.75 GB
Page File   C:\pagefile.sys
A hypervisor has been detected. Features required for Hyper-V will not be displayed.    
```
