### ISSUE TITLE
GetRootFolder problems after every build

### ISSUE THREAD

**Issue by slolife** [madskristensen/WebEssentials2012#37]
Running WE 3.4, VS.NET 2012
========== Build: 23 succeeded, 0 failed, 55 up-to-date, 0 skipped ==========
1/6/2014 12:08:20 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/6/2014 12:08:22 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
1/6/2014 12:08:22 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()

**Comment by adrianp74** [comment]
I can confirm that this is still happening on the latest release, 3.5

**Comment by jtsom** [comment]
Unfortunately, this keeps popping up, without any sign of getting fixed :(

**Comment by PandaWood** [comment]
Still happening in 3.6.5. Thinking of writing an addin to remove WebEssentials exception messages...

**Comment by adrianp74** [comment]
And yet they keep releases new versions.

**Comment by madskristensen** [comment]
@adrianp74 The project is open source. Feel free to send a pull request with a fix
