### ISSUE TITLE
The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

### ISSUE THREAD

**Issue by Tarabass** [madskristensen/WebEssentials2012#55]
After updating _WebEssentials2012_ to the latest version I'm getting an error after building my solutions:

**Parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG)**

OS: _Windows Server 2008 R2 Standard SP1_
VS: _Visual Studio 2012 Professional_
WE: _WebEssentails2021 v3.7_

**Comment by jtsom** [comment]
Join the club. Been like that for several versions...

**Comment by JorgeMCSilva** [comment]
+1 on this

**Comment by hyrmedia** [comment]
+1 (card-carrying club member). I'm guessing this just isn't going to be fixed for the 2012 version, eh?

Here's my info:
Visual Studio Premium 2012 v11.0.61030.00 Update 4
Web Essentials 2012 v3.7
.NET 4.5.51641
etc.

**Comment by madskristensen** [comment]
No work is being done on the 2012 version of Web Essentials at all by me. I would take any pull request, but no one is sending any.

**Comment by jasoncavett** [comment]
Here's a little more on the issue:

```
8/28/2014 4:19:39 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
```

Visual Studio Ultimate 2012
Web Essentials 3.7
.NET 4.5.51641
Windows 7
