### ISSUE TITLE
Root Folder

### ISSUE THREAD

**Issue by LordDelacroix** [madskristensen/WebEssentials2012#87]
5/6/2015 1:42:51 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
5/6/2015 1:42:51 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
5/6/2015 1:42:51 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
5/6/2015 1:42:51 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
5/6/2015 1:42:51 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
5/6/2015 1:42:51 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()

Has development / fixing stopped for VS2012 and Web Essentials 2012?

**Comment by serges147** [comment]
Same problem at Web Essentials 2012 3.8
